---
- name: Test Connection
  hosts: "{{ projects }},&web,&{{ env }}"
  gather_facts: false
  vars:
    dynamic_user: false
  roles:
    - { role: connection, tags: [connection, always] }
    - { role: dynamic-hosts, tags: [dynamic-hosts, always] }

- name: Deploy WP site
  hosts: dynamic_hosts
  gather_facts: false
  remote_user: "{{ web_user }}"
  pre_tasks:
    - name: Ensure repo is valid
      connection: local
      fail:
        msg: |
          Invalid Git repository.
          Ensure that your site's `repo` variable is defined and uses the SSH format
          (example: git@github.com:roots/bedrock.git).
          The `repo` variable is usually defined in `group_vars/all/site_vars.yml`
          or in `{{ project_path }}/vars/{{ env }}/site_vars.yml`.
          More info:
          > https://roots.io/trellis/docs/deploys/
      when: repo is not defined or not repo | match(".*@.*:.*\.git")
  roles:
    - deploy
