---
- name: Test Connection
  hosts: "{{ projects }},&web,&{{ env }}"
  gather_facts: false
  vars:
    dynamic_user: false
  roles:
    - { role: connection, tags: [connection, always] }
    - { role: dynamic-hosts, tags: [dynamic-hosts, always] }

- name: Rollback a Deploy
  hosts: dynamic_hosts
  gather_facts: false
  remote_user: "{{ web_user }}"
  roles:
    - rollback
