---
- name: Test Connection
  hosts: "{{ projects }},&web,&{{ env }}"
  gather_facts: false
  vars:
    dynamic_user: false
  roles:
    - { role: connection, tags: [connection, always] }

- name: Rollback a Deploy
  hosts: "{{ projects }},&web,&{{ env }}"
  remote_user: "{{ web_user }}"
  roles:
    - rollback
