---
- name: Create web root
  file:
    path: "{{ www_root }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory

- name: Create WordPress php-fpm configuration file
  template:
    src: php-fpm.conf.j2
    dest: /etc/php/7.1/fpm/pool.d/wordpress.conf
  notify: reload php-fpm

- name: Disable default PHP-FPM pool
  command: mv /etc/php/7.1/fpm/pool.d/www.conf /etc/php/7.1/fpm/pool.d/www.disabled
  args:
    creates: /etc/php/7.1/fpm/pool.d/www.disabled
  when: disable_default_pool | default(true)
  notify: reload php-fpm

- name: Create Nginx conf for challenges location
  template:
    src: "{{ playbook_dir }}/roles/letsencrypt-general/templates/acme-challenge-location.conf.j2"
    dest: "{{ nginx_path }}/acme-challenge-location.conf"
  notify: reload nginx

- name: Create parent directories for general Nginx includes
  file:
    path: "{{ nginx_path }}/includes.d/{{ item.dest | dirname }}"
    state: directory
  with_items: "{{ nginx_includes_general }}"
  tags: nginx-includes

- name: Template general Nginx includes to includes.d
  template:
    src: "{{ item.src }}"
    dest: "{{ nginx_path }}/includes.d/{{ item.dest }}"
  with_items: "{{ nginx_includes_general }}"
  notify: reload nginx
  tags: nginx-includes
