composer_keep_updated: true
composer_global_packages:
 - { name: hirak/prestissimo }
apt_cache_valid_time: 3600
ntp_timezone: Etc/UTC
ntp_manage_config: true
www_root: /srv/www
ip_whitelist:
  - "{{ (env == 'development') | ternary(ansible_default_ipv4.gateway, ipify_public_ip | default('')) }}"

gzip_assets_on_deploy: true
# Relative to `web`
static_asset_paths:
  - wp/wp-content/plugins
  - wp/wp-includes
  - app/plugins
  - app/themes

# patterns to match for assets' relative paths
# static_asset_pattern: (?!.*exclude_string)(include_string|other_include_string)
static_asset_pattern: .*

static_asset_extensions:
  - js
  - css
  - svg
  - txt
  - md
  - htm
  - html
  - xml
  - json
  - ttf
  - ttc
  - otf
  - eot
  - woff
  - woff2
no_cache_extensions:
  - manifest
  - appcache
  - htm
  - html
  - xml
  - json
cross_domain_font_extensions:
  - ttf
  - ttc
  - otf
  - eot
  - woff
  - woff2

# Values of raw_vars will be wrapped in `{% raw %}` to avoid templating problems if values include `{%` and `{{`.
# Will recurse dicts/lists. `*` is wildcard for one or more dict keys, list indices, or strings. Example:
#   - vault_wordpress_sites.*.*_salt    -- matches vault_wordpress_sites.example.com.env.secure_auth_salt etc.
# Will not function for var names or topmost dict keys that contain a period ('.').
raw_vars:
  - vault_mail_password
  - vault_mysql_root_password
  - vault_users.*.password
  - vault_users.*.salt
  - vault_wordpress_sites
