missing_hosts: "{{ site_hosts_all | difference((current_hosts.stdout | trim).split(' ')) }}"

acme_tiny_commit: '4ed13950c0a9cf61f1ca81ff1874cde1cf48ab32'
acme_tiny_software_directory: /usr/local/letsencrypt
acme_tiny_data_directory: /var/lib/letsencrypt
acme_tiny_challenges_directory: "{{ www_root }}/letsencrypt"

letsencrypt_ca: 'https://acme-v01.api.letsencrypt.org'

letsencrypt_account_key: '{{ acme_tiny_data_directory }}/account.key'

letsencrypt_intermediate_cert_path: /etc/ssl/certs/lets-encrypt-x3-cross-signed.pem
letsencrypt_intermediate_cert_sha256sum: 'e446c5e9dbef9d09ac9f7027c034602492437a05ff6c40011d7235fca639c79a'

letsencrypt_keys_dir: "{{ nginx_ssl_path }}/letsencrypt"
letsencrypt_certs_dir: "{{ nginx_ssl_path }}/letsencrypt"

# the minimum age (in days) after which a certificate will be renewed
letsencrypt_min_renewal_age: 60

# the days of a month the cronjob should be run. Make sure to run it rather often, three times per month is a pretty
# good value. It does not harm to run it often, as it will only regenerate certificates that have passed a certain age
# (60 days by default).
letsencrypt_cronjob_daysofmonth: 1,11,21

designated_child_host_letsencrypt: inventory_hostname == groups[parent_host + '-letsencrypt-sites'] | default(['']) | intersect(ansible_play_batch) | first
