---
- name: restart memcached
  service:
    name: memcached
    state: restarted

- name: reload php-fpm
  service:
    name: php7.1-fpm
    state: reloaded

- name: reload nginx
  command: nginx -t
  notify: perform nginx reload

- name: perform nginx reload
  service:
    name: nginx
    state: reloaded
