---
- name: Show variable values per host
  debug:
    msg: |
      {% for item in show_vars.split(',') %}
      {% set value = (hostvars[inventory_hostname][item + '_merged'][site] if item.endswith('site_vars') else hostvars[inventory_hostname][item]) %}
      {% if value | type_debug == 'unicode' %}
      {{ item }}: {{ value }}
      {% else %}
      {{ item }}:
        {{ value | to_nice_yaml() | indent(2) }}
      {% endif %}
      {% endfor %}
  when: show_vars | default(false)
  tags: show_vars

- import_tasks: database.yml
  tags: wordpress-setup-database

- import_tasks: self-signed-certificate.yml
  tags: wordpress-setup-self-signed-certificate

- import_tasks: nginx-client-cert.yml
  tags: wordpress-setup-nginx-client-cert

- import_tasks: "{{ playbook_dir }}/roles/letsencrypt-sites/tasks/disable_challenge_sites.yml"

- name: Create logs folder of sites
  file:
    path: "{{ www_root }}/{{ site }}/logs"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory

- name: Copy SSL cert
  copy:
    src: "{{ ssl.cert }}"
    dest: "{{ nginx_ssl_path }}/{{ ssl.cert | basename }}"
    mode: 0640
  when: ssl.enabled and ssl.provider == 'manual' and ssl.cert is defined
  notify: reload nginx

- name: Copy SSL key
  copy:
    src: "{{ ssl.key }}"
    dest: "{{ nginx_ssl_path }}/{{ ssl.key | basename }}"
    mode: 0600
  when: ssl.enabled and ssl.provider == 'manual' and ssl.key is defined
  notify: reload nginx

- name: Create WordPress configuration for Nginx
  template:
    src: "{{ nginx_wordpress_site_conf }}"
    dest: "{{ nginx_path }}/sites-available/{{ site }}.conf"
  notify: reload nginx
  tags: nginx-includes

- name: Enable WordPress site
  file:
    src: "{{ nginx_path }}/sites-available/{{ site }}.conf"
    dest: "{{ nginx_path }}/sites-enabled/{{ site }}.conf"
    owner: root
    group: root
    state: link
  notify: reload nginx

- name: Setup WP system cron
  cron:
    name: "{{ site }} WordPress cron"
    minute: "*/15"
    user: "{{ web_user }}"
    job: "cd {{ www_root }}/{{ site }}/{{ current_path | default('current') }} && wp cron event run --due-now > /dev/null 2>&1"
    cron_file: "wordpress-{{ site | replace('.', '_') }}"
    state: "{{ (cron_enabled and not multisite.enabled) | ternary('present', 'absent') }}"

- name: Setup WP Multisite system cron
  cron:
    name: "{{ site }} WordPress network cron"
    minute: "*/30"
    user: "{{ web_user }}"
    job: "cd {{ www_root }}/{{ site }}/{{ current_path | default('current') }} && wp site list --field=url | xargs -n1 -I \\% wp --url=\\% cron event run --due-now > /dev/null 2>&1"
    cron_file: "wordpress-multisite-{{ site | replace('.', '_') }}"
    state: "{{ (cron_enabled and multisite.enabled) | ternary('present', 'absent') }}"
