---
- name: Generate self-signed certificates
  shell: "openssl req -new -newkey rsa:2048 \
    -days 3650 -nodes -x509 -sha256 \
    -extensions req_ext -config <( \
cat <<' EOF'\n
[req]\n
prompt = no\n
distinguished_name = req_dn\n
[req_dn]\n
commonName = {{ site_hosts_canonical | first }}\n
[req_ext]\n
subjectAltName = {{ site_hosts_all | union(multisite_subdomains_wildcards) | map('regex_replace', '(.*)', 'DNS:\\1') | join(',') }}\n
EOF\n
    ) \
    -keyout {{ site | quote }}.key -out {{ site | quote }}.cert"
  args:
    executable: "/bin/bash"
    chdir: "{{ nginx_ssl_path }}"
    creates: "{{ site }}.*"
  when: ssl.enabled and ssl.provider == 'self-signed'
  notify: reload nginx
