---
sshd_ports:
  - 22

sshd_listen_addresses:
  - 0.0.0.0

sshd_protocol: 2

sshd_accept_env: []

sshd_challenge_response_authentication: false

sshd_ciphers_default:
  - chacha20-poly1305@openssh.com
  - aes256-gcm@openssh.com
  - aes128-gcm@openssh.com
  - aes256-ctr
  - aes192-ctr
  - aes128-ctr

sshd_ciphers_extra: []

sshd_host_keys:
  - /etc/ssh/ssh_host_ed25519_key
  - /etc/ssh/ssh_host_rsa_key

sshd_kex_algorithms_default:
  - curve25519-sha256@libssh.org
  - diffie-hellman-group-exchange-sha256

sshd_kex_algorithms_extra: []

sshd_login_grace_time: 30

sshd_macs_default:
  - hmac-sha2-512-etm@openssh.com
  - hmac-sha2-256-etm@openssh.com
  - hmac-ripemd160-etm@openssh.com
  - umac-128-etm@openssh.com
  - hmac-sha2-512
  - hmac-sha2-256
  - hmac-ripemd160

sshd_macs_extra: []

sshd_password_authentication: false
sshd_permit_root_login: true
sshd_print_last_log: false
sshd_print_motd: false
sshd_subsystem: sftp internal-sftp
sshd_tcp_keep_alive: true
sshd_use_pam: true
sshd_x11_forwarding: false
